"""add tournament format

Revision ID: 1610127e126d
Revises: 31398394a636
Create Date: 2026-07-05 19:53:32.537323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1610127e126d'
down_revision: Union[str, None] = '31398394a636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (predating this column) as
    # double-elimination, matching the prior hardcoded behavior.
    op.add_column(
        'tournaments',
        sa.Column(
            'format',
            sa.Enum('SINGLE_ELIMINATION', 'DOUBLE_ELIMINATION', name='tournamentformat'),
            nullable=False,
            server_default='DOUBLE_ELIMINATION',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'format')
    # ### end Alembic commands ###
