"""initial schema

Revision ID: 31398394a636
Revises: 
Create Date: 2026-07-05 19:34:33.136690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31398394a636'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('SETUP', 'IN_PROGRESS', 'COMPLETE', name='tournamentstatus'), nullable=False),
    sa.Column('public_slug', sa.String(length=32), nullable=False),
    sa.Column('manage_token', sa.String(length=64), nullable=False),
    sa.Column('overall_champion_player_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_manage_token'), 'tournaments', ['manage_token'], unique=True)
    op.create_index(op.f('ix_tournaments_public_slug'), 'tournaments', ['public_slug'], unique=True)
    op.create_table('participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_eliminated', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bracket_rounds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('bracket', sa.Enum('WINNERS', 'LOSERS', 'GRAND_FINAL', name='bracket'), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETE', name='roundstatus'), nullable=False),
    sa.Column('waiting_bye_participant_id', sa.Uuid(), nullable=True),
    sa.Column('excluded_participant_id', sa.Uuid(), nullable=True),
    sa.Column('pending_carry_player_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['excluded_participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['waiting_bye_participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'bracket', 'round_number')
    )
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bracket_round_id', sa.Uuid(), nullable=False),
    sa.Column('player_one_id', sa.Uuid(), nullable=False),
    sa.Column('player_two_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bracket_round_id'], ['bracket_rounds.id'], ),
    sa.ForeignKeyConstraint(['player_one_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['player_two_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bracket_round_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('NORMAL', 'TEAM_BYE', 'GRAND_FINAL', 'GRAND_FINAL_RESET', name='matchkind'), nullable=False),
    sa.Column('team_a_id', sa.Uuid(), nullable=True),
    sa.Column('team_b_id', sa.Uuid(), nullable=True),
    sa.Column('winner_team_id', sa.Uuid(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sequence_in_round', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bracket_round_id'], ['bracket_rounds.id'], ),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('teams')
    op.drop_table('bracket_rounds')
    op.drop_table('participants')
    op.drop_index(op.f('ix_tournaments_public_slug'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_manage_token'), table_name='tournaments')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
